perfsonar/pscheduler

pscheduler-core/pscheduler-core/diags
Resolving IP addresses could be slowish. Is there real need to have hostnames?
=> netstat not to resolve IP addresses

scripts/docker/local-demo
If containers have stopped for any reason they won't be removed with `stop` command.
=> Docker local demo to remove even stopped containers

python-pscheduler/pscheduler/pscheduler/limitprocessor/identifier/ipcidrlist.py, python-pscheduler/pscheduler/pscheduler/limitprocessor/identifier/localif.py, python-pscheduler/pscheduler/pscheduler/limitprocessor/identifierset.py, python-pscheduler/python-pscheduler.spec
A frequent issue i ran into when using the default limits file is that very rarely does pscheduler identify my host as 127.0.0.1 when I am running from local host. Instead it usually grabs one of the other ips. I can of course add that IP to the limits, but this is extra work for most people that we'd like to avoid having them do.
This pull requests adds a special keyword 'local' that you can give to an ipcidr list. Example:
```
{
"name": "very-trusted-hosts",
"description": "Hosts we trust",
"type": "ip-cidr-list",
"data": {
"cidrs": [
"local"
]
}
}
```
If it sees this keyword, it will poll the system for the list of interfaces and add all IPv4 and IPv6 addresses to the list. It uses the python-netifaces package, which should be available for all supported operating systems.
=> IP CIDR List support for auto-detecting local IPs

pscheduler-test-snmpget/snmpget/spec-to-cli, pscheduler-test-snmpgetbgm/snmpgetbgm/spec-to-cli
Fixing the issue listed here https://github.com/perfsonar/pscheduler/issues/536 for both snmpget and snmpgetbgm.
Now if "pscheduler task snmpget/snmpgetbgm" is run without any OID, pscheduler.fail will be called with a message saying that at least one oid must be queried.
=> Issue #536 BugFix

pscheduler-test-latency/latency/cli-to-spec, pscheduler-test-latency/latency/limit-passes, pscheduler-test-latency/latency/spec-format, pscheduler-test-latency/latency/validate.py, pscheduler-test-latency/tests/cli-to-spec_test.py, pscheduler-test-latency/tests/limit-is-valid_test.py, pscheduler-test-latency/tests/limit-passes_test.py, pscheduler-test-latency/tests/spec-format_test.py, pscheduler-test-latency/tests/spec-to-cli_test.py, pscheduler-tool-twping/twping/run
Reports latency from destination to source.
=> pscheduler-tool-twping: use reverse flag instead of flip

pscheduler-test-throughput/tests/cli-to-spec_test.py, pscheduler-test-throughput/tests/spec-is-valid_test.py, pscheduler-test-throughput/throughput/cli-to-spec, pscheduler-test-throughput/throughput/participants, pscheduler-test-throughput/throughput/spec-format, pscheduler-test-throughput/throughput/spec-is-valid, pscheduler-test-throughput/throughput/spec-to-cli, pscheduler-test-throughput/throughput/validate.py, pscheduler-tool-iperf2/iperf2/can-run, pscheduler-tool-iperf2/iperf2/run, pscheduler-tool-iperf3/iperf3/can-run, pscheduler-tool-iperf3/iperf3/merged-results, pscheduler-tool-iperf3/iperf3/run
Allows running throughput tests against servers running only
iperf2/iperf3 server on the default port.
=> Add --single-ended flag to iperf2 and iperf3  #456

pscheduler-test-rtt/rtt/cli-to-spec, pscheduler-test-rtt/rtt/participants, pscheduler-test-rtt/rtt/spec-format, pscheduler-test-rtt/rtt/spec-is-valid, pscheduler-test-rtt/rtt/spec-to-cli, pscheduler-test-rtt/rtt/validate.py, pscheduler-tool-ping/ping/can-run, pscheduler-tool-twping/twping/can-run, pscheduler-tool-twping/twping/enumerate, pscheduler-tool-twping/twping/run
Allow twping tool to produce both ``latency`` and ``rtt`` type results.
=> pscheduler-tool-twping: add rtt test support #625

pscheduler-test-latency/latency/result-format
Simple fix to make sure histogram buckets are sorted numerically instead of alphabetically for text output of latency tests.
=> Issue 693: Fixes histogram bucket sorting in latency test CLI output

pscheduler-tool-twping/twping/run
If any of the timestamps are zero we get invalid RTT value.
=> pscheduler-tool-twping: check for zero timestamps #746

python-pscheduler/pscheduler/pscheduler/psurl.py
Fixing issue in psurl where a HTTP request succeeds but returns a status code that is not 200, such as a 201. This change accepts anything in the HTTP success range of 200-299
=> Fixes Issue 812 where HTTP 2XX status codes above 200 are considered failed

python-pscheduler/pscheduler/pscheduler/psurl.py
$ pscheduler troubleshoot
Performing basic troubleshooting of localhost.
localhost:
Measuring MTU... Failed.
SSL: certificate subject name (stretch) does not match target host name 'localhost'
=> Disable TLS host name checking in pycurl

pscheduler-tool-bwctliperf2/debian/changelog, pscheduler-tool-bwctliperf2/debian/control, pscheduler-tool-bwctliperf3/debian/changelog, pscheduler-tool-bwctliperf3/debian/control, pscheduler-tool-bwctlping/debian/changelog, pscheduler-tool-bwctlping/debian/control, pscheduler-tool-bwctltracepath/debian/changelog, pscheduler-tool-bwctltracepath/debian/control, pscheduler-tool-bwctltraceroute/debian/changelog, pscheduler-tool-bwctltraceroute/debian/control
Was missed in previous changes.  Fixes #904
=> Disabling all pscheduler-tool-bwctl* packages in Debian and Ubuntu

pscheduler-archiver-esmond/esmond/esmond_util.py
Checking if unable to normalize measurement-agent with source and just converting to IP if cannot in esmond archiver.
=> Fix for issue 958

postgresql-init/postgresql-init.spec, pscheduler-server/pscheduler-server.spec
This fixes the issue where perfsonar-testpoint won't install because it cannot decide which package that provides "pscheduler-database-init" to use. pscheduler-database-init isn't actually a package, it was just something I added as a _Provides_ back in 4.0 as a way for standalone packages to use "postgresql-init" and for installs with Esmond to use a separate set of packages for initialization. Since Mark  fixed it so esmond works with postgresql-init, this is a false distinction. As such changed the dependency in pscheduler-server to postgresql-init directly and things install as expected.
@mfeit-internet2 added you as reviewer to sanity check. @tonin not sure if there is similar work needed in Debian. This should be the only place we need this change due to the cleanup we have already …
=> Fix for pscheduler-database-init conflict

pscheduler-core/pscheduler-core/Makefile, pscheduler-core/pscheduler-core/debian/tests/control, pscheduler-core/pscheduler-core/debian/tests/metrics, pscheduler-core/pscheduler-core/metrics
Outputs all the statistics available through the API.  It has 2 output format: json (default) and
prometheus to be used with prometheus-node-exporter textfile exporter.
=> Adding a `pscheduler metrics` command for stats

pscheduler-archiver-rabbitmq/rabbitmq/archive
- Enable SSL for amqps URL scheme
- Allow port to be configured
- Change vhost parsing to match pika conventions (omit leading slash)
- Include exchange
=> RabbitMQ archiver fixes

pscheduler-archiver-http/http/archive, pscheduler-archiver-http/http/data-is-valid
Adds a boolean verify-ssl option to default archiver. Default is false which should make it consistent with other pscheduler client using https.
=> Add verify-ssl option to HTTP Archiver

pscheduler-tool-iperf3/iperf3/run
This removes the call in iperf3 server to kill_processes per #1348. Adding this PR to save time if this is solution we want to go with, can dump otherwise.
Looking at history of code, this call (and its predecessors) pre-date the --idle-timeout option in iperf3. I think we can drop it entirely. Also, I wrote a test script to time teh code in question and was able to confirm some of Shawn's hosts see same behavior, so I suspect this is part (definitely not all) of some of the issues they have been seeing with test results.
=> Issue 1348 -Remove iperf3 server kill_processes call

python-pscheduler/pscheduler/pscheduler/jsonval.py
A bug was introduced in 5.1.0 that caused all tests of every type to fail with an "Invalid JSON" error. Error was thrown in at https://github.com/perfsonar/pscheduler/blob/8048b19c208acb49ac6e899f416ba4dd794a2a58/pscheduler-server/pscheduler-server/daemons/runner#L620C24-L620C24 
The problem was that the JSON returned by all tools would not validate since it contains a schema field and fields like "error" and "diags" can be None, which did not bass the string check. I updated jsonval.py to allow for these fields.
=> 5.1.0 JSON Validation Fix

pscheduler-tool-s3-benchmark/s3-benchmark/can-run
Update s3-benchmark tool to allow objects of any non-negative size to be used.
=> Update s3-benchmark tool to allow objects smaller than 1000 bytes

python-pscheduler/pscheduler/unibuild-packaging/rpm/python-pscheduler.spec
=> Update python-pscheduler to start rsyslog if not running

python-pscheduler/pscheduler/pscheduler/clockstate.py
In 5.2.0 branch some of the recent changes made led to 'pscheduler troubleshoot` throwing the following:
```
[root@ps-dev-staging-el9-tk1 andy]# pscheduler troubleshoot
Performing basic troubleshooting of ps-dev-staging-el9-tk1.
ps-dev-staging-el9-tk1:
Checking that host "ps-dev-staging-el9-tk1" resolves... 10.128.0.26
Measuring MTU... 65535 (Local)
Looking for pScheduler... OK.
Fetching API level... 6
Checking clock... Failed.
Unable to fetch clock state: name 'result' is not defined
```
This is just a fix to init the value and confirmed it fixes the issue.
=> Fix in clockstate to initialize result.

pscheduler-server/pscheduler-server/api-server/pschedulerapiserver/runs.py
=> API /runs returns 404 if a task doesn't exist
