- pscheduler-test-throughput/throughput/spec-to-cli
- pscheduler-test-throughput/throughput/validate.py
Update to spec to cli to properly report on all parameters, made validate schemas exportable to help things down the road auto correct.
> fixed spec to cli to properly report all inputs

- pscheduler-tool-iperf3/iperf3/Makefile
- pscheduler-tool-iperf3/iperf3/iperf3.conf
- pscheduler-tool-iperf3/iperf3/iperf3_defaults.py
- pscheduler-tool-iperf3/iperf3/iperf3_utils.py
- pscheduler-tool-iperf3/iperf3/participant-data
- pscheduler-tool-iperf3/iperf3/run
- pscheduler-tool-iperf3/pscheduler-tool-iperf3.spec
Added config file support for iperf3, allows specifying of path to iperf3 and what port the server should boot up on.
> Throughput config file

- scripts/run-pylint
> Improvements to run-pylint

- pscheduler-test-throughput/throughput/result-format
- pscheduler-test-throughput/throughput/throughput_utils.py
- pscheduler-test-throughput/throughput/validate.py
- pscheduler-tool-bwctliperf2/bwctliperf2/iperf_parser.py
- pscheduler-tool-bwctliperf3/bwctliperf3/iperf3_parser.py
- pscheduler-tool-iperf2/iperf2/iperf2_defaults.py
- pscheduler-tool-iperf2/iperf2/iperf2_parser.py
- pscheduler-tool-iperf2/iperf2/run
- pscheduler-tool-iperf3/iperf3/iperf3_parser.py
- pscheduler-tool-nuttcp/nuttcp/nuttcp_parser.py
- python-pscheduler/pscheduler/pscheduler/sinumber.py
Adds a new column "Transferred" to throughput test results showing volume of data moved, along with supporting work in tools.
> Throughput transfer volume

- pscheduler-tool-twping/Makefile
- pscheduler-tool-twping/pscheduler-tool-twping.spec
- pscheduler-tool-twping/tests/can-run_test.py
- pscheduler-tool-twping/tests/duration_test.py
- pscheduler-tool-twping/tests/enumerate_test.py
- pscheduler-tool-twping/tests/merged-results_test.py
- pscheduler-tool-twping/tests/participant-data_test.py
- pscheduler-tool-twping/twping/Makefile
- pscheduler-tool-twping/twping/can-run
- pscheduler-tool-twping/twping/duration
- pscheduler-tool-twping/twping/enumerate
- pscheduler-tool-twping/twping/merged-results
- pscheduler-tool-twping/twping/participant-data
- pscheduler-tool-twping/twping/run
- pscheduler-tool-twping/twping/twping.conf
- pscheduler-tool-twping/twping/twping_defaults.py
- pscheduler-tool-twping/twping/twping_utils.py
- scripts/RPM-BUILD-ORDER.m4
A quick copy of pscheduler-tool-owping using twping, please review.
> Add pscheduler-tool-twping

- pscheduler-test-throughput/throughput/participants
Merging Branch into master. Will also merge into 4.1 after we have a chance to test more.
> Remove BWCTL checks causing lead bind issue for throughput tests

- pscheduler-test-throughput/throughput/participants
This is a pull request to merge fix for BWTL lead bind issue into the 4.1 release branch. I will close this out after we have confirmed it works and want it to be included in 4.1 bugfix release.
> Merge BWCTL Lead Bind Fix Into 4.1 Release branch

- pscheduler-core/pscheduler-core/plot-schedule
Reverts perfsonar/pscheduler#677
> Revert "Issue 676"

- pscheduler-archiver-esmond/esmond/esmond_util.py
> Fixes #698. Checks if reference is None and proceeds normally if it is

- pscheduler-archiver-esmond/esmond/esmond_util.py
- pscheduler-archiver-failer/failer/archive
- pscheduler-archiver-failer/failer/data-is-valid
- pscheduler-server/pscheduler-server/daemons/archiver.raw
- python-pscheduler/pscheduler/pscheduler/program.py
> 4.1.3 into master

- pscheduler-tool-iperf3/iperf3/run
- pscheduler-tool-nuttcp/nuttcp/run
Fixes the setting of CPU affinity passed to numactl when the source is specified.
> Fix CPU affinity when source is specified (issue #844)

- pscheduler-tool-ping/ping/run
- python-pscheduler/pscheduler/pscheduler/ipaddr.py
This is actually issue #886.  The branch was mis-named.
> Do hostname-to-IP resolution properly.  #886

- scripts/PDK/templates/test.TEMPLATE/pscheduler-test-TEMPLATE.spec
- scripts/PDK/templates/tool.TEMPLATE/pscheduler-tool-TEMPLATE.spec
Fixed the python references in the test and tool spec to work with python 3 naming scheme
Fixes #1015
> Issue 1015

- scripts/PDK/templates/test.TEMPLATE/TEMPLATE/spec-format
- scripts/PDK/templates/test.TEMPLATE/TEMPLATE/validate.py
Inconsistent and confusing explanatory comments and copy paste errors from original PDK development
Resolves #1017
> Fixed minor PDK issues

- python-pscheduler/pscheduler/pscheduler/clockstate.py
> Add support for systems running chrony to clockstate

- pscheduler-core/pscheduler-core.spec
- pscheduler-core/pscheduler-core/Makefile
- pscheduler-core/pscheduler-core/diags.raw
This contains #1075 plus a commit that I thought was going straight to 4.3.0
> Added lsof and default archivers.

- pscheduler-test-idle/idle/cli-to-spec
- pscheduler-test-idle/idle/participants
- pscheduler-test-idle/idle/spec-to-cli
- pscheduler-test-idle/idle/validate.py
- pscheduler-tool-sleep/sleep/can-run
- pscheduler-tool-snooze/snooze/can-run
* change spec_is_valid: schema 2
* testing
* test the github working
* support multiple hosts  #1037
* understand schema level 2 #1037
* if there are multiple hosts, they wiil be seperated in the command line
Co-authored-by: jingfei1 <jingfei@umich.com>
> Issue 1037 (#1181)

- pscheduler-server/pscheduler-server/api-server/pschedulerapiserver/access.py
- pscheduler-server/pscheduler-server/api-server/pschedulerapiserver/admin.py
- pscheduler-server/pscheduler-server/api-server/pschedulerapiserver/debug.py.raw
- pscheduler-server/pscheduler-server/api-server/pschedulerapiserver/util.py
There probably won't be a 5.0.9, but in case there is...
> Issue 1413

- scripts/PDK/templates/archiver/Makefile
- scripts/PDK/templates/test/Makefile
- scripts/PDK/templates/test/__PLUGIN_NAME__/Makefile
- scripts/PDK/templates/tool/Makefile
- scripts/PDK/templates/tool/__PLUGIN_NAME__/Makefile
Updated the PDK templates to be compatible with unibuild as used in 5.2.0
> Updated PDK Makefiles to match unibuild

- pscheduler-server/pscheduler-server/api-server/pschedulerapiserver/schedule.py
Lowered the logging level to "debug" instead of "error" for the specific line.
(don't see the reason for level "error")
> fixes-issue-1340

- pscheduler-core/pscheduler-core/troubleshoot
PR to 5.2.0, because 5.3.0 not available
> Fixed - update error messages for troubleshoot. #1331
